# Generated by Django 5.0.1 on 2024-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todolist_options_todolist_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
