# Generated by Django 5.0.1 on 2024-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_options_alter_todolist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.BigIntegerField(),
        ),
    ]
